version: '3.8'

services:
  menuon-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - DATABASE_URL=Server=mysql;Port=3306;Database=menuon;Uid=root;Pwd=${MYSQL_ROOT_PASSWORD};
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: menuon
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
