DROP DATABASE IF EXISTS MENU_ON;
CREATE DATABASE IF NOT EXISTS MENU_ON;
USE MENU_ON;

-- Tabela: LOJA
CREATE TABLE LOJA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(255)  NOT NULL,
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(100),
    IMAGEM_URL VARCHAR(255)  NOT NULL,
    DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Tabela: USUARIO
CREATE TABLE USUARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    CARGO VARCHAR(50) NOT NULL,
    DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Tabela: intermediaria entre usuário e loja
CREATE TABLE USUARIO_LOJA (
    ID_USUARIO INT NOT NULL,
    ID_LOJA INT NOT NULL,
    PRIMARY KEY (ID_USUARIO, ID_LOJA),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
    FOREIGN KEY (ID_LOJA) REFERENCES LOJA(ID)
);

-- Tabela: MENU
CREATE TABLE MENU (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO TEXT NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE,
    ID_LOJA INT,
    FOREIGN KEY (ID_LOJA) REFERENCES LOJA(ID)
);

-- Tabela: CATEGORIA
CREATE TABLE CATEGORIA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO TEXT NOT NULL,
    ORDEM_EXIBICAO INT NOT NULL,
    IMAGEM_URL VARCHAR(255),
    ATIVO BOOLEAN DEFAULT TRUE,
    ID_MENU INT,
    FOREIGN KEY (ID_MENU) REFERENCES MENU(ID)
);

-- Tabela: PRODUTO
CREATE TABLE PRODUTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO TEXT NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    DISPONIVEL BOOLEAN DEFAULT TRUE,
    IMAGEM_URL VARCHAR(255),
    ID_CATEGORIA INT,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID)
);